### PR TITLE
Switch tests to hspec

### PR DESCRIPTION
**Pull request by jsantos17**

### CODE REVIEW

**Comment by jsantos17** [comment]
Looks like hspec-autodiscover doesn't work with GHC 7.6.

**Comment by jpvillaisaza** [comment]
@CristhianMotoche Is there anything to change here if we don't have GHC 7.6.3 in the configuration for Travis?

**Comment by CristhianMotoche** [comment]
We simply need to return in 1 commit.

**Comment by CristhianMotoche** [comment]
I did a rebase of this branch with master. Now, the last 2 commits from @jsantos17 will be enough to use `hspec` for the test.

**Comment by jsl** [comment]
@CristhianMotoche this LGTM. Can you merge it? 

Perhaps later we can make the specs a bit more idiomatic, along the lines of what we did with [dotenv](https://github.com/stackbuilders/dotenv-hs/blob/master/spec/Configuration/DotenvSpec.hs) (i.e., not using so many spec functions, but using more describe blocks to group specs like we do with rspec in Ruby). However, this should be a good enough start for now. Thanks!

**Comment by CristhianMotoche** [comment]
@jsantos17 started this PR, but I can merge it if there is no problem with that.

**Comment by mrkkrp** [comment]
@jsantos17, Can you please rebase on the current master?

**Comment by mrkkrp** [comment]
@jsantos17, OK, I rebased and resolved the conflict for you. Going to merge.

**Pull request merged**
