### PR TITLE
Update to megaparsec-7.0

### PR DESCRIPTION
**Pull request by CristhianMotoche**
## Description:
Update to `megaparsec-7.0.1`. The change didn't break any test.

@juanpaucar Could you take a look please?

### CODE REVIEW

**Comment by CristhianMotoche** [comment]
@juanpaucar `Megaparsec-7` [dropped the support](http://hackage.haskell.org/package/megaparsec-7.0.0/changelog) for GHC 7.8.4. Should we also remove the support for that version of GHC?

**Comment by juanpaucar** [comment]
@CristhianMotoche We will have to drop support for 7.8.4 if we plan to keep megaparsec. You could still use some CPP annotations to distinguish between ghc or megaparsec versions. But, I don't it's worth it. WDYT?

**Comment by CristhianMotoche** [comment]
I don't like the idea of using `CPP`. We can close this PR for now and still use `megaparsec-6`.
Thanks @juanpaucar

**Comment by CristhianMotoche** [comment]
@juanpaucar I reopened the PR. I suppose we will need it for later (when `megaparsec-7` is updated in the stackage nightly).

**Pull request merged**
