### PR TITLE
Benchmarks for inflection functions

### PR DESCRIPTION
**Pull request by CristhianMotoche**
## Description
I started the work for benchmarking this library, as it is suggested in #44. There is a lot of work to do. However, I'd like to discuss this first approach which is based on the benchmarks from https://github.com/mrkkrp/parsers-bench.

@elcuy @sestrella @javcasas @mrkkrp Any suggestion is well received :smiley: 

## TODO:
- [x] Add more benchmarks for the common functions provided by inflections
- [x] Let's discuss these two in a separated issue:
  - [x] Store the results in a file with a timestamp (so that we can make comparisons latter)
  - [x] Which columns from [Weigh](https://hackage.haskell.org/package/weigh-0.0.12/docs/Weigh.html#t:Column) we should record
- [x] Work Load for the functions (how much text?). What about using a simple text from a [book](https://www.gutenberg.org/browse/scores/top).

### CODE REVIEW

**Review by StevenCuasqui — APPROVED** [review]
This resolves #44

**Review by StevenCuasqui — APPROVED** [review]

**Comment by CristhianMotoche** [comment]
Thanks @StevenCuasqui for the review. Unfortunately, the repository requires a maintainer approval in order to be merged. Also, there are some items to improve in this PR that we can include in a separated issue. Does that sound good?

**Comment by StevenCuasqui** [comment]
> Thanks @StevenCuasqui for the review. Unfortunately, the repository requires a maintainer approval in order to be merged. Also, there are some items to improve in this PR that we can include in a separated issue. Does that sound good?



> Thanks @StevenCuasqui for the review. Unfortunately, the repository requires a maintainer approval in order to be merged. Also, there are some items to improve in this PR that we can include in a separated issue. Does that sound good?

I do think is a good idea to discuss the improvements that could be performed, sounds good to me 👍

**Comment by CristhianMotoche** [comment]
I'm getting the following results:
```
Benchmark bench-memory: RUNNING...

Case                                 Allocated  GCs
toUnderscore text-len-100                4,520    0
toUnderscore text-len-10000              4,520    0
toUnderscore text-len-1000000            4,520    0
toUnderscore all text                    4,520    0
toDashed text-len-100                    4,520    0
toDashed text-len-10000                  4,520    0
toDashed text-len-1000000                4,520    0
toDashed all text                        4,520    0
toCamelCased False text-len-100          3,208    0
toCamelCased False text-len-10000        3,208    0
toCamelCased False text-len-1000000      3,208    0
toCamelCased False all text              3,208    0
toHumanized False text-len-100           3,208    0
toHumanized False text-len-10000         3,208    0
toHumanized False text-len-1000000       3,208    0
toHumanized False all text               3,208    0
Benchmark bench-memory: FINISH
```

```
Benchmark bench-speed: RUNNING...
benchmarking toUnderscore/text-len-100
time                 393.0 ns   (392.2 ns .. 394.3 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 394.2 ns   (393.6 ns .. 394.9 ns)
std dev              2.123 ns   (1.779 ns .. 2.805 ns)

benchmarking toUnderscore/text-len-10000
time                 391.6 ns   (391.6 ns .. 391.7 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 391.7 ns   (391.6 ns .. 392.0 ns)
std dev              602.0 ps   (318.8 ps .. 1.158 ns)

benchmarking toUnderscore/text-len-1000000
time                 393.0 ns   (392.3 ns .. 394.4 ns)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 396.2 ns   (393.7 ns .. 399.9 ns)
std dev              10.08 ns   (7.242 ns .. 12.83 ns)
variance introduced by outliers: 35% (moderately inflated)

benchmarking toUnderscore/all text
time                 395.2 ns   (394.8 ns .. 395.7 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 395.3 ns   (395.0 ns .. 395.6 ns)
std dev              943.3 ps   (730.7 ps .. 1.266 ns)

benchmarking toDashed/text-len-100
time                 396.1 ns   (394.9 ns .. 397.8 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 395.8 ns   (395.2 ns .. 396.8 ns)
std dev              2.569 ns   (1.631 ns .. 4.179 ns)

benchmarking toDashed/text-len-10000
time                 394.7 ns   (394.2 ns .. 395.1 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 395.1 ns   (394.5 ns .. 396.4 ns)
std dev              2.836 ns   (1.804 ns .. 4.959 ns)

benchmarking toDashed/text-len-1000000
time                 395.0 ns   (394.2 ns .. 395.9 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 395.8 ns   (395.1 ns .. 397.3 ns)
std dev              3.257 ns   (2.155 ns .. 5.651 ns)

benchmarking toDashed/all text
time                 398.7 ns   (396.2 ns .. 401.3 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 399.0 ns   (397.5 ns .. 401.1 ns)
std dev              5.693 ns   (4.658 ns .. 6.989 ns)
variance introduced by outliers: 14% (moderately inflated)

benchmarking toCamelCased False/text-len-100
time                 278.7 ns   (277.8 ns .. 279.9 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 281.5 ns   (279.5 ns .. 284.3 ns)
std dev              7.617 ns   (5.379 ns .. 9.372 ns)
variance introduced by outliers: 39% (moderately inflated)

benchmarking toCamelCased False/text-len-10000
time                 279.9 ns   (278.9 ns .. 281.4 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 280.1 ns   (279.3 ns .. 281.4 ns)
std dev              3.334 ns   (2.353 ns .. 4.537 ns)
variance introduced by outliers: 11% (moderately inflated)

benchmarking toCamelCased False/text-len-1000000
time                 277.9 ns   (277.5 ns .. 278.5 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 279.3 ns   (278.7 ns .. 280.4 ns)
std dev              2.668 ns   (1.806 ns .. 3.750 ns)

benchmarking toCamelCased False/all text
time                 279.7 ns   (277.1 ns .. 282.5 ns)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 283.0 ns   (280.5 ns .. 286.0 ns)
std dev              9.272 ns   (7.206 ns .. 11.43 ns)
variance introduced by outliers: 48% (moderately inflated)

benchmarking toHumanized False/text-len-100
time                 275.7 ns   (275.1 ns .. 276.8 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 277.0 ns   (276.5 ns .. 277.8 ns)
std dev              2.159 ns   (1.526 ns .. 3.303 ns)

benchmarking toHumanized False/text-len-10000
time                 275.1 ns   (275.0 ns .. 275.2 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 275.1 ns   (275.0 ns .. 275.1 ns)
std dev              194.0 ps   (154.5 ps .. 276.4 ps)

benchmarking toHumanized False/text-len-1000000
time                 274.6 ns   (274.4 ns .. 274.8 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 274.9 ns   (274.8 ns .. 275.0 ns)
std dev              370.5 ps   (278.3 ps .. 467.7 ps)

benchmarking toHumanized False/all text
time                 274.0 ns   (274.0 ns .. 274.0 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 274.0 ns   (273.9 ns .. 274.1 ns)
std dev              233.8 ps   (141.4 ps .. 401.2 ps)

Benchmark bench-speed: FINISH
```

**Comment by CristhianMotoche** [comment]
@Centeno448 Can you please take a new look at this?

**Review by Centeno448 — APPROVED** [review]
LGTM! Thanks Cris

**Pull request merged**
