### PR TITLE
added auxiliary convertion functions

### PR DESCRIPTION
**Pull request by s9gf4ult**

### CODE REVIEW

**Comment by s9gf4ult** [comment]
If you accept this patch it would be nice to see it on hackage.

**Comment by jsl** [comment]
Thanks for the contribution, @s9gf4ult! I've push version 0.1.0.8 to hackage.

**Comment by s9gf4ult** [comment]
```
inflections-0.1.0.7 % diff -r . ../inflections-0.1.0.8 
diff -r ./inflections.cabal ../inflections-0.1.0.8/inflections.cabal
2c2
< version:             0.1.0.7
---
> version:             0.1.0.8
diff -r ./Text/Inflections/Humanize.hs ../inflections-0.1.0.8/Text/Inflections/Humanize.hs
8c8
< -- |Capitalizes the first word and turns underscores into spaces Like titleize,
---
> -- |Capitalizes the first word and turns underscores into spaces. Like titleize,
```

It looks like new version does not contains this path.

**Comment by jsl** [comment]
Hi @s9gf4ult could you provide some more information? Are you seeing a problem with the library? I just pushed some new specs for the functions that you added and it seems to be working.

For some reason I don't see the haddock for the functions you wrote on hackage, but I do see them locally:

http://hackage.haskell.org/package/inflections-0.1.0.8/docs/Text-Inflections.html

**Comment by s9gf4ult** [comment]
Yes. There is no functions either in haddock or in source code:

```
22:31 razor@gazoline /tmp % cabal get inflections
Unpacking to inflections-0.1.0.8/
22:31 razor@gazoline /tmp % cd inflections-0.1.0.8 
22:31 razor@gazoline /tmp/inflections-0.1.0.8 % grep -re 'toUnderscore' *
22:32 razor@gazoline /tmp/inflections-0.1.0.8 % 
```

Looks like you accidently uploaded some wrong archive to hackage.

**Comment by jsl** [comment]
Thanks @s9gf4ult, and sorry about the inconvenience. Let's try again with 0.1.0.9. :)

I just verified that the methods you added are in the source, so we should be good to go this time.

Thanks again for your help!

**Comment by s9gf4ult** [comment]
Cool, thanks.

**Pull request merged**
