### PR TITLE
[WIP] Add documentation for parse functions

### PR DESCRIPTION
**Pull request by CristhianMotoche**
I didn't finish the last PR  #27. Here you can take a look of couple of examples for the `parseCamelCase` and `parseSnakeCase` functions.

EDIT: I'll mark this in WIP because it lacks of enough documentation.

### CODE REVIEW

**Comment by mrkkrp** [comment]
The build will fail until we cover everything.

**Comment by mrkkrp** [comment]
How long will it take for you to finish this? I'm going to switch the library to Megaparsec and other things, there will be a lot of conflicts.

**Comment by mrkkrp** [comment]
Maybe it's better merge what you have so far and you can return to this later (or I'll add enough docs myself anyway)?

**Comment by mrkkrp** [comment]
The PR sort of blocks my plan of actions (right now we need to add enough docs to fix the build, so I think I better merge it unless you plan to finish it quickly).

**Comment by CristhianMotoche** [comment]
Mmm I'll let it to your concern, because I'll be back really later.

**Pull request merged**
