### PR TITLE
Add examples for inflections

### PR DESCRIPTION
**Pull request by CristhianMotoche**
Regarding #54, I added a directory for `examples`:

1) Format the name of the records using `Aeson` instances using `TemplateHaskell`
2)  Prepare the results of a list
3)  TODO: ?

@elcuy Could you take a look, please?

### CODE REVIEW

**Review by StevenCuasqui — APPROVED** [review]
This resolves #54

**Comment by CristhianMotoche** [comment]
It solves #58 partially since it adds just one example.

**Comment by CristhianMotoche** [comment]
Hey @Centeno448 I think these two examples could work for now. I think users can review and come up with more interesting examples than the ones that I wrote here. Sounds good to get these examples merged and close #54 ?

**Review by Centeno448 — APPROVED** [review]
Sounds good.

**Pull request merged**
